# Generated by Django 2.0.6 on 2018-07-31 03:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 31, 3, 39, 33, 950990, tzinfo=utc)),
        ),
    ]
